import Sidebar from '@/components/layout/Sidebar';
import '@/styles/globals.css';
import type { Metadata } from 'next';

import Providers from './provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="flex min-h-screen">
        <Providers>
          <Sidebar />
          <main className="flex-1 overflow-x-hidden px-10 py-8">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
